import type { DemoScenario } from '../../types';

export const HACKATHON_DEMO_SCENARIO: DemoScenario = {
  id: 'student_productivity_evaluation',
  title: 'Research and Recommend Productivity Tool for a Student Team',
  description: 'Evaluates top productivity tools with strict constraints (zero budget, offline access, real-time collaboration) and exhibits autonomous adaptation when initial query is insufficient.',
  goal: 'Find, compare, and recommend the best productivity suite for a student development team with $0 budget, cross-platform support, and real-time collaboration.',
  steps: [
    {
      taskId: 'task_1',
      stage: 'PERCEIVE',
      thought: 'Deconstructing user goal into verifiable constraints: zero budget ($0), real-time collaboration, and multi-platform support.',
      action: 'Decomposing requirements and defining success criteria',
    },
    {
      taskId: 'task_1',
      stage: 'ACT',
      thought: 'Querying persistent memory and recording baseline criteria.',
      action: 'Executing memory tool to store hard constraints',
      tool: 'memory',
    },
    {
      taskId: 'task_2',
      stage: 'DECIDE',
      thought: 'Selecting web_research to retrieve candidate tools and pricing structures.',
      action: 'Dispatching web_research query for student productivity tools',
      tool: 'web_research',
    },
    {
      taskId: 'task_2',
      stage: 'ACT',
      thought: 'Initial search provider returned only 2 candidates. Result is marked insufficient.',
      action: 'Running web_research query (Controlled Insufficient Injection)',
      tool: 'web_research',
    },
    {
      taskId: 'task_2',
      stage: 'EVALUATE',
      thought: 'Evaluation detected confidence 45% (< 70% threshold). Insufficient data: requires at least 5 qualifying tools for comparative ranking.',
      action: 'Evaluator flags failure: Insufficient candidate density',
    },
    {
      taskId: 'task_2',
      stage: 'ADAPT',
      thought: 'Self-healing triggered: Autonomous strategy mutation. Broadening search terms to include verified academic indexes and developer issue trackers.',
      action: 'Pivoting strategy: Re-querying with academic education keywords',
      adaptation: {
        id: 'adapt_demo_1',
        failed_task_id: 'task_2',
        problem: 'Initial query returned only 2 tools. Does not meet 5-tool comparative ranking criterion.',
        decision: 'Broaden search domain to academic directories and developer hubs (Linear, Obsidian, Notion, Trello, Miro).',
        action: 'Re-executed web_research with refined multi-keyword search parameters.',
        result: 'Successfully retrieved 5 candidate tools with pricing and offline capability metrics.',
        previous_tool: 'web_research',
        new_tool: 'web_research',
        new_strategy: 'Academic index & developer sprint tracking expansion',
        failure_reason: 'Data density below criteria threshold',
        status: 'replanned',
        timestamp: new Date().toLocaleTimeString(),
      },
    },
    {
      taskId: 'task_2',
      stage: 'ACT',
      thought: 'Adapted search executed successfully: 5 verified candidates retrieved with complete spec sheets.',
      action: 'Re-executing web_research tool with refined parameters',
      tool: 'web_research',
    },
    {
      taskId: 'task_3',
      stage: 'DECIDE',
      thought: 'Selecting calculator to compute multi-attribute composite utility score for each tool.',
      action: 'Selecting calculator tool for normalized scoring',
      tool: 'calculator',
    },
    {
      taskId: 'task_3',
      stage: 'ACT',
      thought: 'Computing scores: Notion (9.4), Linear (9.2), Obsidian (8.9), Miro (8.6), Trello (8.4).',
      action: 'Executing calculator formula on candidate matrix',
      tool: 'calculator',
    },
    {
      taskId: 'task_4',
      stage: 'DECIDE',
      thought: 'Synthesizing evaluation brief and structured comparison matrix with document_generator.',
      action: 'Dispatching document_generator tool',
      tool: 'document_generator',
    },
    {
      taskId: 'task_4',
      stage: 'ACT',
      thought: 'Generated executive decision brief with trade-offs, pricing tables, and recommendations.',
      action: 'Synthesizing final comparison document',
      tool: 'document_generator',
    },
    {
      taskId: 'task_5',
      stage: 'DECIDE',
      thought: 'Final action requires human safety verification before concluding autonomous workflow.',
      action: 'Triggering human approval safety gate',
      tool: 'human_approval',
      requiresApproval: {
        id: 'appr_demo_1',
        taskId: 'task_5',
        action: 'Approve Recommendation & Final Report Publication',
        tool: 'human_approval',
        parameters: { document: 'Productivity Evaluation Brief v1.0' },
        reason: 'Validates that recommended options meet $0 cost and student team privacy requirements before finalizing.',
        riskLevel: 'high',
        status: 'pending',
        requestedAt: new Date().toLocaleTimeString(),
      },
    },
    {
      taskId: 'task_5',
      stage: 'VERIFY',
      thought: 'Executing final audit: Verifying $0 budget constraint, collaboration support, and offline capabilities.',
      action: 'Auditing success criteria against generated artifact',
      verification: {
        verified: true,
        confidence: 0.96,
        checks: [
          { criterion: 'Goal objective satisfied (Productivity suite identified)', passed: true, detail: 'Notion & Linear recommended' },
          { criterion: 'Zero-cost student constraint validated for all recommendations', passed: true, detail: '100% free tiers confirmed' },
          { criterion: 'Factual verification against 5 distinct productivity tools', passed: true, detail: 'All 5 specs audited' },
          { criterion: 'Algorithmic scoring calculation completed without errors', passed: true, detail: 'Calculator scores mathematically verified' },
        ],
        timestamp: new Date().toLocaleTimeString(),
      },
    },
    {
      taskId: 'task_5',
      stage: 'COMPLETED',
      thought: 'All tasks completed and verified with 96% confidence score.',
      action: 'Autonomous workflow completed successfully',
      finalResult: {
        title: 'Recommended Productivity Stack for Student Teams',
        executiveSummary: 'Empirically audited zero-cost collaboration stack. Notion selected for team knowledge base and sprint documentation; Linear selected for issue tracking and backlog management.',
        recommendations: [
          'Adopt Notion (Student Pro) for team documentation, specs, and meeting notes.',
          'Adopt Linear (Free) for high-velocity issue tracking and sprint management.',
          'Optionally use Obsidian for offline personal knowledge bases.',
        ],
        comparisonTable: {
          headers: ['Tool', 'Specialty', 'Student Cost', 'Offline Support', 'Composite Score'],
          rows: [
            ['Notion', 'All-in-one Wiki & Docs', 'Free (Student)', 'Limited Cache', '9.4 / 10'],
            ['Linear', 'Engineering Sprints', 'Free (Unlimited)', 'Yes (PWA)', '9.2 / 10'],
            ['Obsidian', 'Markdown Graph Notes', 'Free (Local)', '100% Native', '8.9 / 10'],
            ['Trello', 'Kanban Board', 'Free Tier', 'No', '8.4 / 10'],
            ['Miro', 'Whiteboard', 'Free Student Tier', 'No', '8.6 / 10'],
          ],
        },
        verificationNotes: [
          'Zero cost constraint validated for all recommendations.',
          'Cross-platform accessibility confirmed.',
          'Direct real-time collaboration supported.',
        ],
        confidenceScore: 0.96,
        verification: {
          verified: true,
          confidence: 0.96,
          checks: [
            { criterion: 'Goal objective satisfied (Productivity suite identified)', passed: true, detail: 'Notion & Linear recommended' },
            { criterion: 'Zero-cost student constraint validated for all recommendations', passed: true, detail: '100% free tiers confirmed' },
            { criterion: 'Factual verification against 5 distinct productivity tools', passed: true, detail: 'All 5 specs audited' },
            { criterion: 'Algorithmic scoring calculation completed without errors', passed: true, detail: 'Calculator scores mathematically verified' },
          ],
          timestamp: new Date().toLocaleTimeString(),
        },
      },
    },
  ],
};
